baseURL = "https://masb89.github.io/"
defaultContentLanguage = "fr"
disableLanguageSwitchingButton = true
disableLanguages = ["en"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
themesDir = "themes/"
publishDir = "docs/"
title = "Marion Clair | Consultante en rangement"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
languageCode = "en-us"
languageName = ""
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.en.menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[Languages.en.menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[Languages.en.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = "project"
name = "Project"
weight = 3
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[Languages.en.menu.main]]
hasChildren = true
name = "Pages"
weight = 5
[[Languages.en.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "service"
name = "Service"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) Tous droits réservés"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
URL = "about"
name = "À propos"
weight = 1
[[Languages.fr.menu.footer]]
URL = "project"
name = "Galerie"
weight = "2"
[[Languages.fr.menu.footer]]
URL = "service"
name = "Prestations"
weight = 3
[[Languages.fr.menu.footer]]
URL = "contact"
name = "Contact"
weight = "4"
[[Languages.fr.menu.main]]
URL = "/"
name = "Accueil"
weight = 1
[[Languages.fr.menu.main]]
URL = "about"
name = "À propos"
weight = 2
[[Languages.fr.menu.main]]
URL = "project"
name = "Galerie"
weight = 3
[[Languages.fr.menu.main]]
URL = "service"
name = "Prestations"
weight = "5"
[[Languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = "6"
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML"]
[params]
author = "Marion Clair"
contact_form_action = "#"
description = ""
email = "demo@email.com"
google_analitycs_id = ""
location = "Lyon, France"
logo = "images/marionclair.png"
logo_width = "150px"
mobile = "+33123456789"
multi_author = false
[params.cookies]
enable = true
expire_days = 2
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "45.764043"
map_longitude = "4.835659"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/slick/slick.css"
[[params.plugins.js]]
attributes = ""
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "https://www.pinterest.fr/marionclairhome/"
[[params.social]]
icon = "ion-social-instagram-outline"
link = "https://www.instagram.com/marionclairhome/"
